title: Puneet Talwar
description:
Data analysis & Machine Learning | Human Genomics | Quantitative Neuroimaging | Cognitive Neuroscience | Neurodegenerative disorders | Systematic Reviews & Meta-analysis
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
