title: Puneet Talwar
description:
\n Data analysis & Machine Learning
\n Human Genomics
\n Quantitative Neuroimaging
\n Cognitive Neuroscience
\n Neurodegenerative disorders 
\n Systematic Reviews & Meta-analysis
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
